### ISSUE TITLE
Linking CXX executable sfl_cache failed

### ISSUE THREAD

**Issue by hoamle** [YuvalNirkin/find_face_landmarks#10]
I can't seem to link sfl_cache executable, even though OpenBlas is already installed. Any help is much appreciated. I'm on Ubuntu 16.04 LTS and using CMake to compile. 

Btw thanks Nirkin and the colleagues a lot for publishing your implementation to the public.

`/usr/bin/ld: ../sequence_face_landmarks/libsequence_face_landmarks.a(sequence_face_landmarks.cpp.o): undefined reference to symbol 'cblas_sscal'
//opt/OpenBLAS/lib/libopenblas.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
sfl_cache/CMakeFiles/sfl_cache.dir/build.make:114: recipe for target 'sfl_cache/sfl_cache' failed
make[2]: *** [sfl_cache/sfl_cache] Error 1
CMakeFiles/Makefile2:140: recipe for target 'sfl_cache/CMakeFiles/sfl_cache.dir/all' failed
make[1]: *** [sfl_cache/CMakeFiles/sfl_cache.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by YuvalNirkin** [comment]
It means you have to specify OpenBLAS to link with.
This dependency probably comes from OpenCV. To fix this you can either build OpenCV without OpenBLAS or add the OpenBLAS library to the library target using CMake.

**Comment by hoamle** [comment]
Thanks Yuval. I included and linked to the OpenBLAS library, and the build went smoothly.
