### ISSUE TITLE
Undefined function or variable 'find_face_landmarks'.

### ISSUE THREAD

**Issue by elliotresearcher** [YuvalNirkin/find_face_landmarks#11]
hi,
 thanks for code,
when i run this code. it gives error
Undefined function or variable 'find_face_landmarks'.

because there is no function named "find_face_landmarks"
please guide me

**Comment by YuvalNirkin** [comment]
You need to add the function to Matlab's path:
```Matlab
addpath 'path/to/find_face_landmarks/interfaces/matlab'
```

**Comment by elliotresearcher** [comment]
thanks for your reply.
i didn't get your point because "find_face_landmarks" is not available in your code

**Comment by YuvalNirkin** [comment]
You have to build and install the library before you can use it.
If you are on Windows you can download the [binaries](https://github.com/YuvalNirkin/find_face_landmarks/releases).

**Comment by elliotresearcher** [comment]
ok thanks a lot,

**Comment by elliotresearcher** [comment]
little different question, I am sorry for that. I have installed VS 2015, but its in D drive of computer, can you please guide me how i can setup mex compiler in matlab.
when i use mex -setup,it only shows compilers which are available in C.

**Comment by YuvalNirkin** [comment]
This question is not an issue with the library.
You don't need to setup a mex compiler, just download the binaries.

**Comment by elliotresearcher** [comment]
it still gives error
in matlab 2015 error is
Attempt to execute SCRIPT find_face_landmarks as a function:

in matlab 2013 error is
invalid mex file
\interfaces\matlab\find_face_landmarks.mexw64':

**Comment by YuvalNirkin** [comment]
The binaries are for 64-bit Matlab.
You will have to build the library from source.

**Comment by elliotresearcher** [comment]
thanks a lot that every time you help, i am new in this field,can you please little guide me how to make a library for this?I'll highly appreciate it.
