### ISSUE TITLE
Does it have some timeout for face disappearing?

### ISSUE THREAD

**Issue by seovchinnikov** [YuvalNirkin/find_face_landmarks#12]
Hello!
Thank you for your great project!
I'm planning to try your code for face tracking in the crowd.
As I understand from https://github.com/YuvalNirkin/find_face_landmarks/blob/master/sequence_face_landmarks/face_tracker_brisk.cpp
you currently don't implement face removing from unmatched faces list after some timeout (so it can increase fps and help to avoid some false positives matches)

Is it true and what caveats do you have about it?

**Comment by YuvalNirkin** [comment]
Try to use the LBP tracker:
[https://github.com/YuvalNirkin/find_face_landmarks/blob/master/sequence_face_landmarks/face_tracker_lbp.cpp](https://github.com/YuvalNirkin/find_face_landmarks/blob/master/sequence_face_landmarks/face_tracker_lbp.cpp)

It does implement what you suggest but it's a little slower.
