### ISSUE TITLE
I am finding the below issue on (cmake find_face_landmarks) while using your code in c++,mac system

### ISSUE THREAD

**Issue by bmanimsc** [YuvalNirkin/find_face_landmarks#13]
In file included from /usr/local/Cellar/dlib/19.7/include/dlib/gui_core/xlib.h:4:
/usr/local/Cellar/dlib/19.7/include/dlib/gui_core/gui_core_kernel_2.h:11:2: error: "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
#error "DLIB_NO_GUI_SUPPORT is defined so you can't use the GUI code.  Turn DLIB_NO_GUI_SUPPORT off if you want to use it."
 ^
/usr/local/Cellar/dlib/19.7/include/dlib/gui_core/gui_core_kernel_2.h:12:2: error: "Also make sure you have libx11-dev installed on your system"
#error "Also make sure you have libx11-dev installed on your system"
 ^
2 errors generated.

**Comment by YuvalNirkin** [comment]
MacOS is not officially supported.
