### ISSUE TITLE
non-type template argument is not a pointer to       member constant

### ISSUE THREAD

**Issue by yuancorp** [YuvalNirkin/find_face_landmarks#15]
i found some issues when i try to build this program on my MacBook Pro
sfl_viewer_states.h:59:55: error: non-type template argument is not a pointer to
      member constant
            sc::in_state_reaction<EvUpdate, Inactive, (void(Inactive::*)(const EvUpdate&))(&Inactive::onUpdate)>,
                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/haiying7/face/find_face_landmarks/sfl_viewer/sfl_viewer_states.h:60:44: error: expected member name or ';' after declaration
      specifiers
            sc::custom_reaction< EvStart > > reactions;
                                           ^
/Users/haiying7/face/find_face_landmarks/sfl_viewer/sfl_viewer_states.h:73:51: error: non-type template argument is not a pointer to
      member constant
            sc::in_state_reaction<EvSeek, Active, (void(Active::*)(const EvSeek&))(&Active::onSeek)>,

**Comment by YuvalNirkin** [comment]
MacOS is not officially supported but you can try:
```
cmake -DBUILD_SFL_VIEWER=OFF
```
