### ISSUE TITLE
Invalid MEX File even with latest binaries

### ISSUE THREAD

**Issue by HariharaBharathy** [YuvalNirkin/find_face_landmarks#18]
Hi !! I am unable to resolve the below error even after having the latest files on the path. 

Invalid MEX-file
'C:\Users\rjznbz\Documents\MATLAB\find_face_landmarks-1.2-x64-vc14-release\interfaces\matlab\find_face_landmarks.mexw64':
Das angegebene Modul wurde nicht gefunden (The Module can't be found)

![image](https://user-images.githubusercontent.com/35962409/35571705-319695ee-05d3-11e8-9a09-bcf18efb9503.png)

**Comment by YuvalNirkin** [comment]
Did you add the bin directory to windows PATH environment variable?
Do you have a 64-bit Matlab?

**Comment by HariharaBharathy** [comment]
Yes , it worked . Thank you so much :)

**Comment by ali1975** [comment]
Hi dear
I have the problem when I run landmark program on my laptop, I got this message:
Invalid MEX File find_face_landmarks.mexw64: The specified The Module could not be found. I added a bin directory to windows PATH environment variable. Knowing on my desktop it works and I have Matlab 64-bit on the laptop, also I copied all DLL files into Matlab bin.
