### ISSUE TITLE
Unable to find dlib

### ISSUE THREAD

**Issue by eladrich** [YuvalNirkin/find_face_landmarks#2]
I've downloaded the dlib library and compiled it successfully:
mkdir build
cd build
cmake ..
make
sudo make install

However, I keep getting the error that my DLIB_ROOT isn't set when trying to build your lib, though I've tried setting it.
I guess I'm missing something simple but would appreciate the help.

**Comment by YuvalNirkin** [comment]
My "Finddlib.cmake" script is unnecessary and probably causing the issue.
Try to delete or rename the "Finddlib.cmake" file in the find_face_landmarks/cmake directory. CMake  should than be able to find the dlib installation.

**Comment by YuvalNirkin** [comment]
I fixed the problems with Linux, it should work now.
Tested on Ubuntu 15.10 with Matlab 2015a 64-bit.
