### ISSUE TITLE
Attempt to execute SCRIPT find_face_landmarks as a function:

### ISSUE THREAD

**Issue by omair50** [YuvalNirkin/find_face_landmarks#3]
Dear, I downloaded pre-compiled library and tried to run on a single still image by using following command "frames = find_face_landmarks(modelFile, 'img.jpg');" but it gives an error 

Attempt to execute SCRIPT find_face_landmarks as a function:
/home/omair530/FaceRegistration/find_face_landmarks_1_1/interfaces/matlab/find_face_landmarks.m

Any solution ?

**Comment by YuvalNirkin** [comment]
The precompiled binaries are only available on Windows currently. You will have to build from source on Linux.

**Comment by alirazaee** [comment]
Hello
I am using matlab 2017 for find_facial_lanfmarks, I did the steps explained but the matlab wont be able to find the function find_facial_landmarks like below

>> frame = Find_face_landmarks(modelFile, I);
Undefined function or variable 'Find_face_landmarks'.

**Comment by YuvalNirkin** [comment]
It's "find_face_landmarks" not "Find_face_landmarks".
