### ISSUE TITLE
Pre-Compiled Mex File Invalid

### ISSUE THREAD

**Issue by sbillin** [YuvalNirkin/find_face_landmarks#4]
I'm unable to execute the pre-compiled mex file on windows.  My system is running:
64-bit Windows 7
64-bit Matlab 2016b

When calling the find_face_landmarks function as described in the Matlab tutorial I get the following error:

frames = find_face_landmarks(modelFile, videoFile);
Invalid MEX-file
<my_path>\find_face_landmarks-1.1-x64-vc14-release\interfaces\matlab\find_face_landmarks.mexw64':
The specified module could not
be found..

I understand that this error happens when a mex file is dependent on an external dll that cannot be found.  I have added the bin folder containing the opencv dlls to my path.

Unfortunately, Matlab doesn't tell me what dll is missing.  However, when I directly run one of the executables in the bin folder (sfl_cache.exe for example), these executables fail with a system error because "opencv_face310.dll" is missing.

So find_face_landmarks.mexw64 may be dependent on opencv_face310.dll?  This dll is not in the bin folder and is also not a part of the standard opencv3.1 package (I tried compiling opencv3.1 to see if I could generate my own version of this dll and no luck).

I really appreciate any help you can offer.  Thanks!

**Comment by YuvalNirkin** [comment]
Thank you for the detailed description, the dll is indeed missing!
opencv_face310 is part of OpenCV's extra modules:
[https://github.com/opencv/opencv_contrib](https://github.com/opencv/opencv_contrib)

I uploaded the binaries with the missing dll, please download them again:
[https://github.com/YuvalNirkin/find_face_landmarks/releases/download/1.1/find_face_landmarks-1.1-x64-vc14-release.zip](https://github.com/YuvalNirkin/find_face_landmarks/releases/download/1.1/find_face_landmarks-1.1-x64-vc14-release.zip)

Let me know if this solved your problem,
Yuval

**Comment by sbillin** [comment]
It's working now with added the added dll.  Thanks a lot!!
