### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by ieyer** [YuvalNirkin/find_face_landmarks#5]
In member function ‘void sfl::FaceTrackerLBP::match(const std::__cxx11::list<std::unique_ptr<sfl::TrackedFaceLBP> >&, const std::vector<sfl::CandidateFace>&, std::set<long unsigned int>&, std::vector<sfl::Face*>&, int)’:
/home/huangw/workspace/find_face_landmarks/sequence_face_landmarks/face_tracker_lbp.cpp:291:56: error: invalid initialization of non-const reference of type ‘std::_Rb_tree_const_iterator<long unsigned int>&’ from an rvalue of type ‘std::set<long unsigned int>::iterator {aka std::_Rb_tree_const_iterator<long unsigned int>}’
                 auto& tracked_it = tracked_indices.find(tracked_ind);
                                                        ^
/home/huangw/workspace/find_face_landmarks/sequence_face_landmarks/face_tracker_lbp.cpp:293:50: error: invalid initialization of non-const reference of type ‘std::_Rb_tree_const_iterator<long unsigned int>&’ from an rvalue of type ‘std::set<long unsigned int>::iterator {aka std::_Rb_tree_const_iterator<long unsigned int>}’
                 auto& cand_it = cand_indices.find(cand_ind);
                                                  ^
sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/build.make:110: recipe for target 'sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/face_tracker_lbp.cpp.o' failed
make[2]: *** [sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/face_tracker_lbp.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/all' failed
make[1]: *** [sequence_face_landmarks/CMakeFiles/sequence_face_landmarks.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by YuvalNirkin** [comment]
Thank you for the feedback,
I fixed the compilation error, please pull the latest version.

Let me know if this solved the problem.
