### ISSUE TITLE
code speed

### ISSUE THREAD

**Issue by zrr1991** [YuvalNirkin/find_face_landmarks#7]
Hi, YuvalNirkin.
     I want to use your code to do something, but some errors appeared  when I cmake the file, and I deal with these errors one by one, and there still exist some error. Because I'm in a hurry, I think maybe I can confirm the fps of the method when tracking, would mind tell me?
   Thank you very much!
 Best Zhang.

**Comment by YuvalNirkin** [comment]
If you build dlib with SSE4 or AVX instructions, the code will run at real-time performance (~30 fps) on resolutions of 640X480 or less.

**Comment by zrr1991** [comment]
Thank you for your reply!
Best wishes！







At 2017-05-12 18:05:44, "Yuval Nirkin" <notifications@github.com> wrote:


If you build dlib with SSE4 or AVX instructions, the code will run at real-time performance (~30 fps) on resolutions of 640X480 or less.
