### ISSUE TITLE
New binaries

### ISSUE THREAD

**Issue by russkel** [YuvalNirkin/find_face_landmarks#8]
Hi Yuval,

Is it possible to get new binaries compiled from master for Windows? I'm having some issues using the most recent binaries (and I haven't got a windows compiler toolchain yet, installing VS now).

```
﻿>> x = find_face_landmarks('models/shape_predictor_68_face_landmarks.dat', 'input/anuclass01.JPG', 1, 1, 0);
>> x

x = 

  struct with fields:

     faces: []
     width: 0
    height: 0
```

Where as the exact same command worked fine on my MacOS setup with the libraries I compiled myself.

Russ

**Comment by YuvalNirkin** [comment]
The binaries for Windows are working well on my system and I can't release new binaries right now.
Try building with Visual Studio.
Anyway it seems that no faces were detected in that particular image, try a different image maybe or play with the scales (try 1:3).

**Comment by russkel** [comment]
That specific image was tested on MacOS and had results. I finally got compiling to work on windows (fun) and now it works correctly:
```
>> x = find_face_landmarks('models/shape_predictor_68_face_landmarks.dat', 'input/anuclass01.JPG', 1, 1, 0);
>> x

x = 

  struct with fields:

     faces: [1×46 struct]
     width: 4608
    height: 3072
```

This matches my MacOS result...

What version of MATLAB are you using?

**Comment by YuvalNirkin** [comment]
I am glad it's working now and that you enjoyed compiling it ;)
I am using MATLAB R2015a but any MATLAB version that supports MEX files should work.

That's a lot of faces for one image... now I am curious what are you working on?

Thanks for the star :)

**Comment by russkel** [comment]
Okay, maybe compatibility with 2017a isn't great with those binaries..

It's nothing all that special, it's for an assignment for a Computer Vision course. Detect faces in a class photo and then recognise those faces from a bunch of self portraits the students took. I was hoping to find a Kazemi face landmark implementation in MATLAB but was unable to find one, and I don't think I have enough time to research everything required so I can implement it myself. This dlib wrapper has proven very useful :). Nothing exciting like face-swapping I'm afraid.

**Comment by YuvalNirkin** [comment]
Oh cool, good luck in the course!

**Comment by russkel** [comment]
Thanks Yuval.
