### ISSUE TITLE
Invalid MEX-file

### ISSUE THREAD

**Issue by vmthanh** [YuvalNirkin/find_face_landmarks#9]
Hi. 
I am using your library to find the facial landmark by Dlib in Matlab. 
But the problem occur when I try to run your example in Matlan:
frame = find_face_landmarks(modelFile, I); 

Error:
Invalid MEX-file
'/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64':
Missing symbol 'sqlite3_auto_extension' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_blob' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_double' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_int' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_int64' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_null' required by
'/usr/lib/libgdal.so.1->/usr/local/lib/libopencv_imgcodecs.so.3.2->/usr/local/lib/libopencv_highgui.so.3.2->/home/thanhvo/Downloads/find_face_landmarks-1.2/interfaces/matlab/find_face_landmarks_mex/find_face_landmarks.mexa64'
Missing symbol 'sqlite3_bind_text' required by
....
It is very long.
It will be very helpful if you could help. My computer runs in Ubuntu 16.04 with Matlab R2017a. I have installed Dlib, OpenCV also.
Best regards.
Thanh.

**Comment by YuvalNirkin** [comment]
Probably Matlab can't find the sqlite3 library.
Try to add it's location to the LD_LIBRARY_PATH environment variable or just build OpenCV without gdal.

**Comment by YuvalNirkin** [comment]
I hope you solved the problem.
I am closing this issue.
